# build
FROM node:18-alpine AS builder
WORKDIR /app
COPY src/Frontend/package*.json ./
RUN npm ci
COPY src/Frontend .
RUN npm run build

# serve
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
